<?php
/**
 * DsAudioObjectRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InfocenterUpdate-TEST-V2
 *
 * Infocenter Update API
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace InfocenterUpdate\Client\Model;

use \ArrayAccess;
use \InfocenterUpdate\Client\ObjectSerializer;

/**
 * DsAudioObjectRequest Class Doc Comment
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DsAudioObjectRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AudioObjectRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'content_size' => 'string',
        'content_url' => 'string',
        'embed_url' => 'string',
        'height' => 'string',
        'width' => 'string',
        'caption' => 'map[string,string]',
        'content_reference_time' => '\DateTime',
        'copyright_year' => 'int',
        'encoding_format' => 'string',
        'is_accessible_for_free' => 'bool',
        'thumbnail_url' => 'string',
        'in_language' => 'string',
        'category' => 'string[]',
        'tag' => 'string[]',
        'contained_in_place' => 'string[]',
        'photo' => '\InfocenterUpdate\Client\Model\DsImageObjectRequest[]',
        'source_id' => 'string',
        'desired_vertex_root_node_id' => 'string',
        'data_governance' => '\InfocenterUpdate\Client\Model\DsDataGovernanceRequest',
        'additional_property' => '\InfocenterUpdate\Client\Model\DsPropertyValueRequest[]',
        'external_ids' => '\InfocenterUpdate\Client\Model\DsExternalIds',
        'auto_translate' => 'bool',
        'publish' => 'bool',
        'is_deleted' => 'bool',
        'name' => 'map[string,string]',
        'alternate_name' => 'map[string,string]',
        'description' => 'map[string,string]',
        'disambiguating_description' => 'map[string,string]',
        'image' => '\InfocenterUpdate\Client\Model\DsImageObjectRequest',
        'same_as' => 'string',
        'url' => 'string',
        'additional_type' => 'string',
        'link' => '\InfocenterUpdate\Client\Model\DsLinkRequest[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'content_size' => null,
        'content_url' => null,
        'embed_url' => null,
        'height' => null,
        'width' => null,
        'caption' => null,
        'content_reference_time' => 'date-time',
        'copyright_year' => 'int32',
        'encoding_format' => null,
        'is_accessible_for_free' => null,
        'thumbnail_url' => null,
        'in_language' => null,
        'category' => null,
        'tag' => null,
        'contained_in_place' => null,
        'photo' => null,
        'source_id' => null,
        'desired_vertex_root_node_id' => null,
        'data_governance' => null,
        'additional_property' => null,
        'external_ids' => null,
        'auto_translate' => null,
        'publish' => null,
        'is_deleted' => null,
        'name' => null,
        'alternate_name' => null,
        'description' => null,
        'disambiguating_description' => null,
        'image' => null,
        'same_as' => null,
        'url' => null,
        'additional_type' => null,
        'link' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'content_size' => 'contentSize',
        'content_url' => 'contentUrl',
        'embed_url' => 'embedUrl',
        'height' => 'height',
        'width' => 'width',
        'caption' => 'caption',
        'content_reference_time' => 'contentReferenceTime',
        'copyright_year' => 'copyrightYear',
        'encoding_format' => 'encodingFormat',
        'is_accessible_for_free' => 'isAccessibleForFree',
        'thumbnail_url' => 'thumbnailUrl',
        'in_language' => 'inLanguage',
        'category' => 'category',
        'tag' => 'tag',
        'contained_in_place' => 'containedInPlace',
        'photo' => 'photo',
        'source_id' => 'sourceId',
        'desired_vertex_root_node_id' => 'desiredVertexRootNodeId',
        'data_governance' => 'dataGovernance',
        'additional_property' => 'additionalProperty',
        'external_ids' => 'externalIds',
        'auto_translate' => 'autoTranslate',
        'publish' => 'publish',
        'is_deleted' => 'isDeleted',
        'name' => 'name',
        'alternate_name' => 'alternateName',
        'description' => 'description',
        'disambiguating_description' => 'disambiguatingDescription',
        'image' => 'image',
        'same_as' => 'sameAs',
        'url' => 'url',
        'additional_type' => 'additionalType',
        'link' => 'link'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'content_size' => 'setContentSize',
        'content_url' => 'setContentUrl',
        'embed_url' => 'setEmbedUrl',
        'height' => 'setHeight',
        'width' => 'setWidth',
        'caption' => 'setCaption',
        'content_reference_time' => 'setContentReferenceTime',
        'copyright_year' => 'setCopyrightYear',
        'encoding_format' => 'setEncodingFormat',
        'is_accessible_for_free' => 'setIsAccessibleForFree',
        'thumbnail_url' => 'setThumbnailUrl',
        'in_language' => 'setInLanguage',
        'category' => 'setCategory',
        'tag' => 'setTag',
        'contained_in_place' => 'setContainedInPlace',
        'photo' => 'setPhoto',
        'source_id' => 'setSourceId',
        'desired_vertex_root_node_id' => 'setDesiredVertexRootNodeId',
        'data_governance' => 'setDataGovernance',
        'additional_property' => 'setAdditionalProperty',
        'external_ids' => 'setExternalIds',
        'auto_translate' => 'setAutoTranslate',
        'publish' => 'setPublish',
        'is_deleted' => 'setIsDeleted',
        'name' => 'setName',
        'alternate_name' => 'setAlternateName',
        'description' => 'setDescription',
        'disambiguating_description' => 'setDisambiguatingDescription',
        'image' => 'setImage',
        'same_as' => 'setSameAs',
        'url' => 'setUrl',
        'additional_type' => 'setAdditionalType',
        'link' => 'setLink'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'content_size' => 'getContentSize',
        'content_url' => 'getContentUrl',
        'embed_url' => 'getEmbedUrl',
        'height' => 'getHeight',
        'width' => 'getWidth',
        'caption' => 'getCaption',
        'content_reference_time' => 'getContentReferenceTime',
        'copyright_year' => 'getCopyrightYear',
        'encoding_format' => 'getEncodingFormat',
        'is_accessible_for_free' => 'getIsAccessibleForFree',
        'thumbnail_url' => 'getThumbnailUrl',
        'in_language' => 'getInLanguage',
        'category' => 'getCategory',
        'tag' => 'getTag',
        'contained_in_place' => 'getContainedInPlace',
        'photo' => 'getPhoto',
        'source_id' => 'getSourceId',
        'desired_vertex_root_node_id' => 'getDesiredVertexRootNodeId',
        'data_governance' => 'getDataGovernance',
        'additional_property' => 'getAdditionalProperty',
        'external_ids' => 'getExternalIds',
        'auto_translate' => 'getAutoTranslate',
        'publish' => 'getPublish',
        'is_deleted' => 'getIsDeleted',
        'name' => 'getName',
        'alternate_name' => 'getAlternateName',
        'description' => 'getDescription',
        'disambiguating_description' => 'getDisambiguatingDescription',
        'image' => 'getImage',
        'same_as' => 'getSameAs',
        'url' => 'getUrl',
        'additional_type' => 'getAdditionalType',
        'link' => 'getLink'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['content_size'] = isset($data['content_size']) ? $data['content_size'] : null;
        $this->container['content_url'] = isset($data['content_url']) ? $data['content_url'] : null;
        $this->container['embed_url'] = isset($data['embed_url']) ? $data['embed_url'] : null;
        $this->container['height'] = isset($data['height']) ? $data['height'] : null;
        $this->container['width'] = isset($data['width']) ? $data['width'] : null;
        $this->container['caption'] = isset($data['caption']) ? $data['caption'] : null;
        $this->container['content_reference_time'] = isset($data['content_reference_time']) ? $data['content_reference_time'] : null;
        $this->container['copyright_year'] = isset($data['copyright_year']) ? $data['copyright_year'] : null;
        $this->container['encoding_format'] = isset($data['encoding_format']) ? $data['encoding_format'] : null;
        $this->container['is_accessible_for_free'] = isset($data['is_accessible_for_free']) ? $data['is_accessible_for_free'] : null;
        $this->container['thumbnail_url'] = isset($data['thumbnail_url']) ? $data['thumbnail_url'] : null;
        $this->container['in_language'] = isset($data['in_language']) ? $data['in_language'] : null;
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['tag'] = isset($data['tag']) ? $data['tag'] : null;
        $this->container['contained_in_place'] = isset($data['contained_in_place']) ? $data['contained_in_place'] : null;
        $this->container['photo'] = isset($data['photo']) ? $data['photo'] : null;
        $this->container['source_id'] = isset($data['source_id']) ? $data['source_id'] : null;
        $this->container['desired_vertex_root_node_id'] = isset($data['desired_vertex_root_node_id']) ? $data['desired_vertex_root_node_id'] : null;
        $this->container['data_governance'] = isset($data['data_governance']) ? $data['data_governance'] : null;
        $this->container['additional_property'] = isset($data['additional_property']) ? $data['additional_property'] : null;
        $this->container['external_ids'] = isset($data['external_ids']) ? $data['external_ids'] : null;
        $this->container['auto_translate'] = isset($data['auto_translate']) ? $data['auto_translate'] : null;
        $this->container['publish'] = isset($data['publish']) ? $data['publish'] : null;
        $this->container['is_deleted'] = isset($data['is_deleted']) ? $data['is_deleted'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['alternate_name'] = isset($data['alternate_name']) ? $data['alternate_name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['disambiguating_description'] = isset($data['disambiguating_description']) ? $data['disambiguating_description'] : null;
        $this->container['image'] = isset($data['image']) ? $data['image'] : null;
        $this->container['same_as'] = isset($data['same_as']) ? $data['same_as'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['additional_type'] = isset($data['additional_type']) ? $data['additional_type'] : null;
        $this->container['link'] = isset($data['link']) ? $data['link'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets content_size
     *
     * @return string
     */
    public function getContentSize()
    {
        return $this->container['content_size'];
    }

    /**
     * Sets content_size
     *
     * @param string $content_size content_size
     *
     * @return $this
     */
    public function setContentSize($content_size)
    {
        $this->container['content_size'] = $content_size;

        return $this;
    }

    /**
     * Gets content_url
     *
     * @return string
     */
    public function getContentUrl()
    {
        return $this->container['content_url'];
    }

    /**
     * Sets content_url
     *
     * @param string $content_url content_url
     *
     * @return $this
     */
    public function setContentUrl($content_url)
    {
        $this->container['content_url'] = $content_url;

        return $this;
    }

    /**
     * Gets embed_url
     *
     * @return string
     */
    public function getEmbedUrl()
    {
        return $this->container['embed_url'];
    }

    /**
     * Sets embed_url
     *
     * @param string $embed_url embed_url
     *
     * @return $this
     */
    public function setEmbedUrl($embed_url)
    {
        $this->container['embed_url'] = $embed_url;

        return $this;
    }

    /**
     * Gets height
     *
     * @return string
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param string $height height
     *
     * @return $this
     */
    public function setHeight($height)
    {
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets width
     *
     * @return string
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param string $width width
     *
     * @return $this
     */
    public function setWidth($width)
    {
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets caption
     *
     * @return map[string,string]
     */
    public function getCaption()
    {
        return $this->container['caption'];
    }

    /**
     * Sets caption
     *
     * @param map[string,string] $caption caption
     *
     * @return $this
     */
    public function setCaption($caption)
    {
        $this->container['caption'] = $caption;

        return $this;
    }

    /**
     * Gets content_reference_time
     *
     * @return \DateTime
     */
    public function getContentReferenceTime()
    {
        return $this->container['content_reference_time'];
    }

    /**
     * Sets content_reference_time
     *
     * @param \DateTime $content_reference_time content_reference_time
     *
     * @return $this
     */
    public function setContentReferenceTime($content_reference_time)
    {
        $this->container['content_reference_time'] = $content_reference_time;

        return $this;
    }

    /**
     * Gets copyright_year
     *
     * @return int
     */
    public function getCopyrightYear()
    {
        return $this->container['copyright_year'];
    }

    /**
     * Sets copyright_year
     *
     * @param int $copyright_year copyright_year
     *
     * @return $this
     */
    public function setCopyrightYear($copyright_year)
    {
        $this->container['copyright_year'] = $copyright_year;

        return $this;
    }

    /**
     * Gets encoding_format
     *
     * @return string
     */
    public function getEncodingFormat()
    {
        return $this->container['encoding_format'];
    }

    /**
     * Sets encoding_format
     *
     * @param string $encoding_format encoding_format
     *
     * @return $this
     */
    public function setEncodingFormat($encoding_format)
    {
        $this->container['encoding_format'] = $encoding_format;

        return $this;
    }

    /**
     * Gets is_accessible_for_free
     *
     * @return bool
     */
    public function getIsAccessibleForFree()
    {
        return $this->container['is_accessible_for_free'];
    }

    /**
     * Sets is_accessible_for_free
     *
     * @param bool $is_accessible_for_free is_accessible_for_free
     *
     * @return $this
     */
    public function setIsAccessibleForFree($is_accessible_for_free)
    {
        $this->container['is_accessible_for_free'] = $is_accessible_for_free;

        return $this;
    }

    /**
     * Gets thumbnail_url
     *
     * @return string
     */
    public function getThumbnailUrl()
    {
        return $this->container['thumbnail_url'];
    }

    /**
     * Sets thumbnail_url
     *
     * @param string $thumbnail_url thumbnail_url
     *
     * @return $this
     */
    public function setThumbnailUrl($thumbnail_url)
    {
        $this->container['thumbnail_url'] = $thumbnail_url;

        return $this;
    }

    /**
     * Gets in_language
     *
     * @return string
     */
    public function getInLanguage()
    {
        return $this->container['in_language'];
    }

    /**
     * Sets in_language
     *
     * @param string $in_language in_language
     *
     * @return $this
     */
    public function setInLanguage($in_language)
    {
        $this->container['in_language'] = $in_language;

        return $this;
    }

    /**
     * Gets category
     *
     * @return string[]
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param string[] $category category
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets tag
     *
     * @return string[]
     */
    public function getTag()
    {
        return $this->container['tag'];
    }

    /**
     * Sets tag
     *
     * @param string[] $tag tag
     *
     * @return $this
     */
    public function setTag($tag)
    {
        $this->container['tag'] = $tag;

        return $this;
    }

    /**
     * Gets contained_in_place
     *
     * @return string[]
     */
    public function getContainedInPlace()
    {
        return $this->container['contained_in_place'];
    }

    /**
     * Sets contained_in_place
     *
     * @param string[] $contained_in_place contained_in_place
     *
     * @return $this
     */
    public function setContainedInPlace($contained_in_place)
    {
        $this->container['contained_in_place'] = $contained_in_place;

        return $this;
    }

    /**
     * Gets photo
     *
     * @return \InfocenterUpdate\Client\Model\DsImageObjectRequest[]
     */
    public function getPhoto()
    {
        return $this->container['photo'];
    }

    /**
     * Sets photo
     *
     * @param \InfocenterUpdate\Client\Model\DsImageObjectRequest[] $photo photo
     *
     * @return $this
     */
    public function setPhoto($photo)
    {
        $this->container['photo'] = $photo;

        return $this;
    }

    /**
     * Gets source_id
     *
     * @return string
     */
    public function getSourceId()
    {
        return $this->container['source_id'];
    }

    /**
     * Sets source_id
     *
     * @param string $source_id source_id
     *
     * @return $this
     */
    public function setSourceId($source_id)
    {
        $this->container['source_id'] = $source_id;

        return $this;
    }

    /**
     * Gets desired_vertex_root_node_id
     *
     * @return string
     */
    public function getDesiredVertexRootNodeId()
    {
        return $this->container['desired_vertex_root_node_id'];
    }

    /**
     * Sets desired_vertex_root_node_id
     *
     * @param string $desired_vertex_root_node_id desired_vertex_root_node_id
     *
     * @return $this
     */
    public function setDesiredVertexRootNodeId($desired_vertex_root_node_id)
    {
        $this->container['desired_vertex_root_node_id'] = $desired_vertex_root_node_id;

        return $this;
    }

    /**
     * Gets data_governance
     *
     * @return \InfocenterUpdate\Client\Model\DsDataGovernanceRequest
     */
    public function getDataGovernance()
    {
        return $this->container['data_governance'];
    }

    /**
     * Sets data_governance
     *
     * @param \InfocenterUpdate\Client\Model\DsDataGovernanceRequest $data_governance data_governance
     *
     * @return $this
     */
    public function setDataGovernance($data_governance)
    {
        $this->container['data_governance'] = $data_governance;

        return $this;
    }

    /**
     * Gets additional_property
     *
     * @return \InfocenterUpdate\Client\Model\DsPropertyValueRequest[]
     */
    public function getAdditionalProperty()
    {
        return $this->container['additional_property'];
    }

    /**
     * Sets additional_property
     *
     * @param \InfocenterUpdate\Client\Model\DsPropertyValueRequest[] $additional_property additional_property
     *
     * @return $this
     */
    public function setAdditionalProperty($additional_property)
    {
        $this->container['additional_property'] = $additional_property;

        return $this;
    }

    /**
     * Gets external_ids
     *
     * @return \InfocenterUpdate\Client\Model\DsExternalIds
     */
    public function getExternalIds()
    {
        return $this->container['external_ids'];
    }

    /**
     * Sets external_ids
     *
     * @param \InfocenterUpdate\Client\Model\DsExternalIds $external_ids external_ids
     *
     * @return $this
     */
    public function setExternalIds($external_ids)
    {
        $this->container['external_ids'] = $external_ids;

        return $this;
    }

    /**
     * Gets auto_translate
     *
     * @return bool
     */
    public function getAutoTranslate()
    {
        return $this->container['auto_translate'];
    }

    /**
     * Sets auto_translate
     *
     * @param bool $auto_translate auto_translate
     *
     * @return $this
     */
    public function setAutoTranslate($auto_translate)
    {
        $this->container['auto_translate'] = $auto_translate;

        return $this;
    }

    /**
     * Gets publish
     *
     * @return bool
     */
    public function getPublish()
    {
        return $this->container['publish'];
    }

    /**
     * Sets publish
     *
     * @param bool $publish publish
     *
     * @return $this
     */
    public function setPublish($publish)
    {
        $this->container['publish'] = $publish;

        return $this;
    }

    /**
     * Gets is_deleted
     *
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->container['is_deleted'];
    }

    /**
     * Sets is_deleted
     *
     * @param bool $is_deleted is_deleted
     *
     * @return $this
     */
    public function setIsDeleted($is_deleted)
    {
        $this->container['is_deleted'] = $is_deleted;

        return $this;
    }

    /**
     * Gets name
     *
     * @return map[string,string]
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param map[string,string] $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets alternate_name
     *
     * @return map[string,string]
     */
    public function getAlternateName()
    {
        return $this->container['alternate_name'];
    }

    /**
     * Sets alternate_name
     *
     * @param map[string,string] $alternate_name alternate_name
     *
     * @return $this
     */
    public function setAlternateName($alternate_name)
    {
        $this->container['alternate_name'] = $alternate_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return map[string,string]
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param map[string,string] $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets disambiguating_description
     *
     * @return map[string,string]
     */
    public function getDisambiguatingDescription()
    {
        return $this->container['disambiguating_description'];
    }

    /**
     * Sets disambiguating_description
     *
     * @param map[string,string] $disambiguating_description disambiguating_description
     *
     * @return $this
     */
    public function setDisambiguatingDescription($disambiguating_description)
    {
        $this->container['disambiguating_description'] = $disambiguating_description;

        return $this;
    }

    /**
     * Gets image
     *
     * @return \InfocenterUpdate\Client\Model\DsImageObjectRequest
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param \InfocenterUpdate\Client\Model\DsImageObjectRequest $image image
     *
     * @return $this
     */
    public function setImage($image)
    {
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets same_as
     *
     * @return string
     */
    public function getSameAs()
    {
        return $this->container['same_as'];
    }

    /**
     * Sets same_as
     *
     * @param string $same_as same_as
     *
     * @return $this
     */
    public function setSameAs($same_as)
    {
        $this->container['same_as'] = $same_as;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets additional_type
     *
     * @return string
     */
    public function getAdditionalType()
    {
        return $this->container['additional_type'];
    }

    /**
     * Sets additional_type
     *
     * @param string $additional_type additional_type
     *
     * @return $this
     */
    public function setAdditionalType($additional_type)
    {
        $this->container['additional_type'] = $additional_type;

        return $this;
    }

    /**
     * Gets link
     *
     * @return \InfocenterUpdate\Client\Model\DsLinkRequest[]
     */
    public function getLink()
    {
        return $this->container['link'];
    }

    /**
     * Sets link
     *
     * @param \InfocenterUpdate\Client\Model\DsLinkRequest[] $link link
     *
     * @return $this
     */
    public function setLink($link)
    {
        $this->container['link'] = $link;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
