<?php
/**
 * DsRatingRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InfocenterUpdate-TEST-V2
 *
 * Infocenter Update API
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace InfocenterUpdate\Client\Model;

use \ArrayAccess;
use \InfocenterUpdate\Client\ObjectSerializer;

/**
 * DsRatingRequest Class Doc Comment
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DsRatingRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RatingRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'best_rating' => 'double',
        'rating_value' => 'double',
        'review_aspect' => 'string',
        'worst_rating' => 'double',
        'garni' => 'bool',
        'superior' => 'bool',
        'author' => '\InfocenterUpdate\Client\Model\DsPartnerRequest',
        'name' => 'map[string,string]',
        'alternate_name' => 'map[string,string]',
        'description' => 'map[string,string]',
        'disambiguating_description' => 'map[string,string]',
        'image' => '\InfocenterUpdate\Client\Model\DsImageObjectRequest',
        'same_as' => 'string',
        'url' => 'string',
        'additional_type' => 'string',
        'link' => '\InfocenterUpdate\Client\Model\DsLinkRequest[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'best_rating' => 'double',
        'rating_value' => 'double',
        'review_aspect' => null,
        'worst_rating' => 'double',
        'garni' => null,
        'superior' => null,
        'author' => null,
        'name' => null,
        'alternate_name' => null,
        'description' => null,
        'disambiguating_description' => null,
        'image' => null,
        'same_as' => null,
        'url' => null,
        'additional_type' => null,
        'link' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'best_rating' => 'bestRating',
        'rating_value' => 'ratingValue',
        'review_aspect' => 'reviewAspect',
        'worst_rating' => 'worstRating',
        'garni' => 'garni',
        'superior' => 'superior',
        'author' => 'author',
        'name' => 'name',
        'alternate_name' => 'alternateName',
        'description' => 'description',
        'disambiguating_description' => 'disambiguatingDescription',
        'image' => 'image',
        'same_as' => 'sameAs',
        'url' => 'url',
        'additional_type' => 'additionalType',
        'link' => 'link'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'best_rating' => 'setBestRating',
        'rating_value' => 'setRatingValue',
        'review_aspect' => 'setReviewAspect',
        'worst_rating' => 'setWorstRating',
        'garni' => 'setGarni',
        'superior' => 'setSuperior',
        'author' => 'setAuthor',
        'name' => 'setName',
        'alternate_name' => 'setAlternateName',
        'description' => 'setDescription',
        'disambiguating_description' => 'setDisambiguatingDescription',
        'image' => 'setImage',
        'same_as' => 'setSameAs',
        'url' => 'setUrl',
        'additional_type' => 'setAdditionalType',
        'link' => 'setLink'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'best_rating' => 'getBestRating',
        'rating_value' => 'getRatingValue',
        'review_aspect' => 'getReviewAspect',
        'worst_rating' => 'getWorstRating',
        'garni' => 'getGarni',
        'superior' => 'getSuperior',
        'author' => 'getAuthor',
        'name' => 'getName',
        'alternate_name' => 'getAlternateName',
        'description' => 'getDescription',
        'disambiguating_description' => 'getDisambiguatingDescription',
        'image' => 'getImage',
        'same_as' => 'getSameAs',
        'url' => 'getUrl',
        'additional_type' => 'getAdditionalType',
        'link' => 'getLink'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['best_rating'] = isset($data['best_rating']) ? $data['best_rating'] : null;
        $this->container['rating_value'] = isset($data['rating_value']) ? $data['rating_value'] : null;
        $this->container['review_aspect'] = isset($data['review_aspect']) ? $data['review_aspect'] : null;
        $this->container['worst_rating'] = isset($data['worst_rating']) ? $data['worst_rating'] : null;
        $this->container['garni'] = isset($data['garni']) ? $data['garni'] : null;
        $this->container['superior'] = isset($data['superior']) ? $data['superior'] : null;
        $this->container['author'] = isset($data['author']) ? $data['author'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['alternate_name'] = isset($data['alternate_name']) ? $data['alternate_name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['disambiguating_description'] = isset($data['disambiguating_description']) ? $data['disambiguating_description'] : null;
        $this->container['image'] = isset($data['image']) ? $data['image'] : null;
        $this->container['same_as'] = isset($data['same_as']) ? $data['same_as'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['additional_type'] = isset($data['additional_type']) ? $data['additional_type'] : null;
        $this->container['link'] = isset($data['link']) ? $data['link'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets best_rating
     *
     * @return double
     */
    public function getBestRating()
    {
        return $this->container['best_rating'];
    }

    /**
     * Sets best_rating
     *
     * @param double $best_rating best_rating
     *
     * @return $this
     */
    public function setBestRating($best_rating)
    {
        $this->container['best_rating'] = $best_rating;

        return $this;
    }

    /**
     * Gets rating_value
     *
     * @return double
     */
    public function getRatingValue()
    {
        return $this->container['rating_value'];
    }

    /**
     * Sets rating_value
     *
     * @param double $rating_value rating_value
     *
     * @return $this
     */
    public function setRatingValue($rating_value)
    {
        $this->container['rating_value'] = $rating_value;

        return $this;
    }

    /**
     * Gets review_aspect
     *
     * @return string
     */
    public function getReviewAspect()
    {
        return $this->container['review_aspect'];
    }

    /**
     * Sets review_aspect
     *
     * @param string $review_aspect review_aspect
     *
     * @return $this
     */
    public function setReviewAspect($review_aspect)
    {
        $this->container['review_aspect'] = $review_aspect;

        return $this;
    }

    /**
     * Gets worst_rating
     *
     * @return double
     */
    public function getWorstRating()
    {
        return $this->container['worst_rating'];
    }

    /**
     * Sets worst_rating
     *
     * @param double $worst_rating worst_rating
     *
     * @return $this
     */
    public function setWorstRating($worst_rating)
    {
        $this->container['worst_rating'] = $worst_rating;

        return $this;
    }

    /**
     * Gets garni
     *
     * @return bool
     */
    public function getGarni()
    {
        return $this->container['garni'];
    }

    /**
     * Sets garni
     *
     * @param bool $garni garni
     *
     * @return $this
     */
    public function setGarni($garni)
    {
        $this->container['garni'] = $garni;

        return $this;
    }

    /**
     * Gets superior
     *
     * @return bool
     */
    public function getSuperior()
    {
        return $this->container['superior'];
    }

    /**
     * Sets superior
     *
     * @param bool $superior superior
     *
     * @return $this
     */
    public function setSuperior($superior)
    {
        $this->container['superior'] = $superior;

        return $this;
    }

    /**
     * Gets author
     *
     * @return \InfocenterUpdate\Client\Model\DsPartnerRequest
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param \InfocenterUpdate\Client\Model\DsPartnerRequest $author author
     *
     * @return $this
     */
    public function setAuthor($author)
    {
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets name
     *
     * @return map[string,string]
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param map[string,string] $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets alternate_name
     *
     * @return map[string,string]
     */
    public function getAlternateName()
    {
        return $this->container['alternate_name'];
    }

    /**
     * Sets alternate_name
     *
     * @param map[string,string] $alternate_name alternate_name
     *
     * @return $this
     */
    public function setAlternateName($alternate_name)
    {
        $this->container['alternate_name'] = $alternate_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return map[string,string]
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param map[string,string] $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets disambiguating_description
     *
     * @return map[string,string]
     */
    public function getDisambiguatingDescription()
    {
        return $this->container['disambiguating_description'];
    }

    /**
     * Sets disambiguating_description
     *
     * @param map[string,string] $disambiguating_description disambiguating_description
     *
     * @return $this
     */
    public function setDisambiguatingDescription($disambiguating_description)
    {
        $this->container['disambiguating_description'] = $disambiguating_description;

        return $this;
    }

    /**
     * Gets image
     *
     * @return \InfocenterUpdate\Client\Model\DsImageObjectRequest
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param \InfocenterUpdate\Client\Model\DsImageObjectRequest $image image
     *
     * @return $this
     */
    public function setImage($image)
    {
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets same_as
     *
     * @return string
     */
    public function getSameAs()
    {
        return $this->container['same_as'];
    }

    /**
     * Sets same_as
     *
     * @param string $same_as same_as
     *
     * @return $this
     */
    public function setSameAs($same_as)
    {
        $this->container['same_as'] = $same_as;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets additional_type
     *
     * @return string
     */
    public function getAdditionalType()
    {
        return $this->container['additional_type'];
    }

    /**
     * Sets additional_type
     *
     * @param string $additional_type additional_type
     *
     * @return $this
     */
    public function setAdditionalType($additional_type)
    {
        $this->container['additional_type'] = $additional_type;

        return $this;
    }

    /**
     * Gets link
     *
     * @return \InfocenterUpdate\Client\Model\DsLinkRequest[]
     */
    public function getLink()
    {
        return $this->container['link'];
    }

    /**
     * Sets link
     *
     * @param \InfocenterUpdate\Client\Model\DsLinkRequest[] $link link
     *
     * @return $this
     */
    public function setLink($link)
    {
        $this->container['link'] = $link;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
