<?php
/**
 * DsTourRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InfocenterUpdate-TEST-V2
 *
 * Infocenter Update API
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace InfocenterUpdate\Client\Model;

use \ArrayAccess;
use \InfocenterUpdate\Client\ObjectSerializer;

/**
 * DsTourRequest Class Doc Comment
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DsTourRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TourRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'winter_activity' => 'bool',
        'length' => 'double',
        'time' => 'int',
        'elevation_json' => 'string',
        'elevation' => '\InfocenterUpdate\Client\Model\DsTourElevationRequest',
        'rating_json' => 'string',
        'rating' => '\InfocenterUpdate\Client\Model\DsTourRatingRequest',
        'season' => '\InfocenterUpdate\Client\Model\DsTourSeasonRequest',
        'risk_potential' => 'int',
        'state' => 'string',
        'title' => 'map[string,string]',
        'starting_point_description' => 'map[string,string]',
        'safety_guidelines' => 'map[string,string]',
        'equipment' => 'map[string,string]',
        'tip' => 'map[string,string]',
        'additional_information' => 'map[string,string]',
        'destination' => 'map[string,string]',
        'track_signage' => 'map[string,string]',
        'literature' => 'map[string,string]',
        'maps' => 'map[string,string]',
        'duration' => 'string',
        'geo_destination' => '\InfocenterUpdate\Client\Model\DsGeoCoordinatesRequest',
        'available_language' => 'string[]',
        'slogan' => 'string',
        'branch_code' => 'string',
        'address' => '\InfocenterUpdate\Client\Model\DsPostalAddressRequest',
        'fax_number' => 'string',
        'geo' => '\InfocenterUpdate\Client\Model\DsGeoCoordinatesRequest',
        'geo_shape' => '\InfocenterUpdate\Client\Model\DsGeoShapeRequest',
        'has_map' => 'string',
        'is_accessible_for_free' => 'bool',
        'maximum_attendee_capacity' => 'int',
        'opening_hours_specification' => '\InfocenterUpdate\Client\Model\DsOpeningHoursSpecificationRequest[]',
        'logo' => '\InfocenterUpdate\Client\Model\DsImageObjectRequest',
        'photo' => '\InfocenterUpdate\Client\Model\DsImageObjectRequest[]',
        'public_access' => 'bool',
        'smoking_allowed' => 'bool',
        'special_opening_hours_specification' => '\InfocenterUpdate\Client\Model\DsOpeningHoursSpecificationRequest[]',
        'telephone' => 'string',
        'tourist_type' => 'string',
        'located' => 'string[]',
        'copyright' => 'map[string,string]',
        'detailed_information' => 'map[string,\InfocenterUpdate\Client\Model\DsIEnumerableString]',
        'title_teaser' => 'map[string,string]',
        'text_teaser' => 'map[string,string]',
        'public_transport' => 'map[string,string]',
        'getting_there' => 'map[string,string]',
        'opening_hours' => 'map[string,string]',
        'parking' => 'map[string,string]',
        'directions' => 'map[string,string]',
        'fees' => 'map[string,string]',
        'osm_id' => 'string',
        'category' => 'string[]',
        'tag' => 'string[]',
        'audio' => '\InfocenterUpdate\Client\Model\DsAudioObjectRequest[]',
        'video' => '\InfocenterUpdate\Client\Model\DsVideoObjectRequest[]',
        'amenity_feature' => '\InfocenterUpdate\Client\Model\DsLocationFeatureSpecificationRequest[]',
        'located_at' => 'string',
        'source_id' => 'string',
        'desired_vertex_root_node_id' => 'string',
        'data_governance' => '\InfocenterUpdate\Client\Model\DsDataGovernanceRequest',
        'additional_property' => '\InfocenterUpdate\Client\Model\DsPropertyValueRequest[]',
        'external_ids' => '\InfocenterUpdate\Client\Model\DsExternalIds',
        'auto_translate' => 'bool',
        'publish' => 'bool',
        'is_deleted' => 'bool',
        'name' => 'map[string,string]',
        'alternate_name' => 'map[string,string]',
        'description' => 'map[string,string]',
        'disambiguating_description' => 'map[string,string]',
        'image' => '\InfocenterUpdate\Client\Model\DsImageObjectRequest',
        'same_as' => 'string',
        'url' => 'string',
        'additional_type' => 'string',
        'link' => '\InfocenterUpdate\Client\Model\DsLinkRequest[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'winter_activity' => null,
        'length' => 'double',
        'time' => 'int32',
        'elevation_json' => null,
        'elevation' => null,
        'rating_json' => null,
        'rating' => null,
        'season' => null,
        'risk_potential' => 'int32',
        'state' => null,
        'title' => null,
        'starting_point_description' => null,
        'safety_guidelines' => null,
        'equipment' => null,
        'tip' => null,
        'additional_information' => null,
        'destination' => null,
        'track_signage' => null,
        'literature' => null,
        'maps' => null,
        'duration' => null,
        'geo_destination' => null,
        'available_language' => null,
        'slogan' => null,
        'branch_code' => null,
        'address' => null,
        'fax_number' => null,
        'geo' => null,
        'geo_shape' => null,
        'has_map' => null,
        'is_accessible_for_free' => null,
        'maximum_attendee_capacity' => 'int32',
        'opening_hours_specification' => null,
        'logo' => null,
        'photo' => null,
        'public_access' => null,
        'smoking_allowed' => null,
        'special_opening_hours_specification' => null,
        'telephone' => null,
        'tourist_type' => null,
        'located' => null,
        'copyright' => null,
        'detailed_information' => null,
        'title_teaser' => null,
        'text_teaser' => null,
        'public_transport' => null,
        'getting_there' => null,
        'opening_hours' => null,
        'parking' => null,
        'directions' => null,
        'fees' => null,
        'osm_id' => null,
        'category' => null,
        'tag' => null,
        'audio' => null,
        'video' => null,
        'amenity_feature' => null,
        'located_at' => null,
        'source_id' => null,
        'desired_vertex_root_node_id' => null,
        'data_governance' => null,
        'additional_property' => null,
        'external_ids' => null,
        'auto_translate' => null,
        'publish' => null,
        'is_deleted' => null,
        'name' => null,
        'alternate_name' => null,
        'description' => null,
        'disambiguating_description' => null,
        'image' => null,
        'same_as' => null,
        'url' => null,
        'additional_type' => null,
        'link' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'winter_activity' => 'winterActivity',
        'length' => 'length',
        'time' => 'time',
        'elevation_json' => 'elevationJson',
        'elevation' => 'elevation',
        'rating_json' => 'ratingJson',
        'rating' => 'rating',
        'season' => 'season',
        'risk_potential' => 'riskPotential',
        'state' => 'state',
        'title' => 'title',
        'starting_point_description' => 'startingPointDescription',
        'safety_guidelines' => 'safetyGuidelines',
        'equipment' => 'equipment',
        'tip' => 'tip',
        'additional_information' => 'additionalInformation',
        'destination' => 'destination',
        'track_signage' => 'trackSignage',
        'literature' => 'literature',
        'maps' => 'maps',
        'duration' => 'duration',
        'geo_destination' => 'geoDestination',
        'available_language' => 'availableLanguage',
        'slogan' => 'slogan',
        'branch_code' => 'branchCode',
        'address' => 'address',
        'fax_number' => 'faxNumber',
        'geo' => 'geo',
        'geo_shape' => 'geoShape',
        'has_map' => 'hasMap',
        'is_accessible_for_free' => 'isAccessibleForFree',
        'maximum_attendee_capacity' => 'maximumAttendeeCapacity',
        'opening_hours_specification' => 'openingHoursSpecification',
        'logo' => 'logo',
        'photo' => 'photo',
        'public_access' => 'publicAccess',
        'smoking_allowed' => 'smokingAllowed',
        'special_opening_hours_specification' => 'specialOpeningHoursSpecification',
        'telephone' => 'telephone',
        'tourist_type' => 'touristType',
        'located' => 'located',
        'copyright' => 'copyright',
        'detailed_information' => 'detailedInformation',
        'title_teaser' => 'titleTeaser',
        'text_teaser' => 'textTeaser',
        'public_transport' => 'publicTransport',
        'getting_there' => 'gettingThere',
        'opening_hours' => 'openingHours',
        'parking' => 'parking',
        'directions' => 'directions',
        'fees' => 'fees',
        'osm_id' => 'osm_id',
        'category' => 'category',
        'tag' => 'tag',
        'audio' => 'audio',
        'video' => 'video',
        'amenity_feature' => 'amenityFeature',
        'located_at' => 'locatedAt',
        'source_id' => 'sourceId',
        'desired_vertex_root_node_id' => 'desiredVertexRootNodeId',
        'data_governance' => 'dataGovernance',
        'additional_property' => 'additionalProperty',
        'external_ids' => 'externalIds',
        'auto_translate' => 'autoTranslate',
        'publish' => 'publish',
        'is_deleted' => 'isDeleted',
        'name' => 'name',
        'alternate_name' => 'alternateName',
        'description' => 'description',
        'disambiguating_description' => 'disambiguatingDescription',
        'image' => 'image',
        'same_as' => 'sameAs',
        'url' => 'url',
        'additional_type' => 'additionalType',
        'link' => 'link'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'winter_activity' => 'setWinterActivity',
        'length' => 'setLength',
        'time' => 'setTime',
        'elevation_json' => 'setElevationJson',
        'elevation' => 'setElevation',
        'rating_json' => 'setRatingJson',
        'rating' => 'setRating',
        'season' => 'setSeason',
        'risk_potential' => 'setRiskPotential',
        'state' => 'setState',
        'title' => 'setTitle',
        'starting_point_description' => 'setStartingPointDescription',
        'safety_guidelines' => 'setSafetyGuidelines',
        'equipment' => 'setEquipment',
        'tip' => 'setTip',
        'additional_information' => 'setAdditionalInformation',
        'destination' => 'setDestination',
        'track_signage' => 'setTrackSignage',
        'literature' => 'setLiterature',
        'maps' => 'setMaps',
        'duration' => 'setDuration',
        'geo_destination' => 'setGeoDestination',
        'available_language' => 'setAvailableLanguage',
        'slogan' => 'setSlogan',
        'branch_code' => 'setBranchCode',
        'address' => 'setAddress',
        'fax_number' => 'setFaxNumber',
        'geo' => 'setGeo',
        'geo_shape' => 'setGeoShape',
        'has_map' => 'setHasMap',
        'is_accessible_for_free' => 'setIsAccessibleForFree',
        'maximum_attendee_capacity' => 'setMaximumAttendeeCapacity',
        'opening_hours_specification' => 'setOpeningHoursSpecification',
        'logo' => 'setLogo',
        'photo' => 'setPhoto',
        'public_access' => 'setPublicAccess',
        'smoking_allowed' => 'setSmokingAllowed',
        'special_opening_hours_specification' => 'setSpecialOpeningHoursSpecification',
        'telephone' => 'setTelephone',
        'tourist_type' => 'setTouristType',
        'located' => 'setLocated',
        'copyright' => 'setCopyright',
        'detailed_information' => 'setDetailedInformation',
        'title_teaser' => 'setTitleTeaser',
        'text_teaser' => 'setTextTeaser',
        'public_transport' => 'setPublicTransport',
        'getting_there' => 'setGettingThere',
        'opening_hours' => 'setOpeningHours',
        'parking' => 'setParking',
        'directions' => 'setDirections',
        'fees' => 'setFees',
        'osm_id' => 'setOsmId',
        'category' => 'setCategory',
        'tag' => 'setTag',
        'audio' => 'setAudio',
        'video' => 'setVideo',
        'amenity_feature' => 'setAmenityFeature',
        'located_at' => 'setLocatedAt',
        'source_id' => 'setSourceId',
        'desired_vertex_root_node_id' => 'setDesiredVertexRootNodeId',
        'data_governance' => 'setDataGovernance',
        'additional_property' => 'setAdditionalProperty',
        'external_ids' => 'setExternalIds',
        'auto_translate' => 'setAutoTranslate',
        'publish' => 'setPublish',
        'is_deleted' => 'setIsDeleted',
        'name' => 'setName',
        'alternate_name' => 'setAlternateName',
        'description' => 'setDescription',
        'disambiguating_description' => 'setDisambiguatingDescription',
        'image' => 'setImage',
        'same_as' => 'setSameAs',
        'url' => 'setUrl',
        'additional_type' => 'setAdditionalType',
        'link' => 'setLink'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'winter_activity' => 'getWinterActivity',
        'length' => 'getLength',
        'time' => 'getTime',
        'elevation_json' => 'getElevationJson',
        'elevation' => 'getElevation',
        'rating_json' => 'getRatingJson',
        'rating' => 'getRating',
        'season' => 'getSeason',
        'risk_potential' => 'getRiskPotential',
        'state' => 'getState',
        'title' => 'getTitle',
        'starting_point_description' => 'getStartingPointDescription',
        'safety_guidelines' => 'getSafetyGuidelines',
        'equipment' => 'getEquipment',
        'tip' => 'getTip',
        'additional_information' => 'getAdditionalInformation',
        'destination' => 'getDestination',
        'track_signage' => 'getTrackSignage',
        'literature' => 'getLiterature',
        'maps' => 'getMaps',
        'duration' => 'getDuration',
        'geo_destination' => 'getGeoDestination',
        'available_language' => 'getAvailableLanguage',
        'slogan' => 'getSlogan',
        'branch_code' => 'getBranchCode',
        'address' => 'getAddress',
        'fax_number' => 'getFaxNumber',
        'geo' => 'getGeo',
        'geo_shape' => 'getGeoShape',
        'has_map' => 'getHasMap',
        'is_accessible_for_free' => 'getIsAccessibleForFree',
        'maximum_attendee_capacity' => 'getMaximumAttendeeCapacity',
        'opening_hours_specification' => 'getOpeningHoursSpecification',
        'logo' => 'getLogo',
        'photo' => 'getPhoto',
        'public_access' => 'getPublicAccess',
        'smoking_allowed' => 'getSmokingAllowed',
        'special_opening_hours_specification' => 'getSpecialOpeningHoursSpecification',
        'telephone' => 'getTelephone',
        'tourist_type' => 'getTouristType',
        'located' => 'getLocated',
        'copyright' => 'getCopyright',
        'detailed_information' => 'getDetailedInformation',
        'title_teaser' => 'getTitleTeaser',
        'text_teaser' => 'getTextTeaser',
        'public_transport' => 'getPublicTransport',
        'getting_there' => 'getGettingThere',
        'opening_hours' => 'getOpeningHours',
        'parking' => 'getParking',
        'directions' => 'getDirections',
        'fees' => 'getFees',
        'osm_id' => 'getOsmId',
        'category' => 'getCategory',
        'tag' => 'getTag',
        'audio' => 'getAudio',
        'video' => 'getVideo',
        'amenity_feature' => 'getAmenityFeature',
        'located_at' => 'getLocatedAt',
        'source_id' => 'getSourceId',
        'desired_vertex_root_node_id' => 'getDesiredVertexRootNodeId',
        'data_governance' => 'getDataGovernance',
        'additional_property' => 'getAdditionalProperty',
        'external_ids' => 'getExternalIds',
        'auto_translate' => 'getAutoTranslate',
        'publish' => 'getPublish',
        'is_deleted' => 'getIsDeleted',
        'name' => 'getName',
        'alternate_name' => 'getAlternateName',
        'description' => 'getDescription',
        'disambiguating_description' => 'getDisambiguatingDescription',
        'image' => 'getImage',
        'same_as' => 'getSameAs',
        'url' => 'getUrl',
        'additional_type' => 'getAdditionalType',
        'link' => 'getLink'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['winter_activity'] = isset($data['winter_activity']) ? $data['winter_activity'] : null;
        $this->container['length'] = isset($data['length']) ? $data['length'] : null;
        $this->container['time'] = isset($data['time']) ? $data['time'] : null;
        $this->container['elevation_json'] = isset($data['elevation_json']) ? $data['elevation_json'] : null;
        $this->container['elevation'] = isset($data['elevation']) ? $data['elevation'] : null;
        $this->container['rating_json'] = isset($data['rating_json']) ? $data['rating_json'] : null;
        $this->container['rating'] = isset($data['rating']) ? $data['rating'] : null;
        $this->container['season'] = isset($data['season']) ? $data['season'] : null;
        $this->container['risk_potential'] = isset($data['risk_potential']) ? $data['risk_potential'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['starting_point_description'] = isset($data['starting_point_description']) ? $data['starting_point_description'] : null;
        $this->container['safety_guidelines'] = isset($data['safety_guidelines']) ? $data['safety_guidelines'] : null;
        $this->container['equipment'] = isset($data['equipment']) ? $data['equipment'] : null;
        $this->container['tip'] = isset($data['tip']) ? $data['tip'] : null;
        $this->container['additional_information'] = isset($data['additional_information']) ? $data['additional_information'] : null;
        $this->container['destination'] = isset($data['destination']) ? $data['destination'] : null;
        $this->container['track_signage'] = isset($data['track_signage']) ? $data['track_signage'] : null;
        $this->container['literature'] = isset($data['literature']) ? $data['literature'] : null;
        $this->container['maps'] = isset($data['maps']) ? $data['maps'] : null;
        $this->container['duration'] = isset($data['duration']) ? $data['duration'] : null;
        $this->container['geo_destination'] = isset($data['geo_destination']) ? $data['geo_destination'] : null;
        $this->container['available_language'] = isset($data['available_language']) ? $data['available_language'] : null;
        $this->container['slogan'] = isset($data['slogan']) ? $data['slogan'] : null;
        $this->container['branch_code'] = isset($data['branch_code']) ? $data['branch_code'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['fax_number'] = isset($data['fax_number']) ? $data['fax_number'] : null;
        $this->container['geo'] = isset($data['geo']) ? $data['geo'] : null;
        $this->container['geo_shape'] = isset($data['geo_shape']) ? $data['geo_shape'] : null;
        $this->container['has_map'] = isset($data['has_map']) ? $data['has_map'] : null;
        $this->container['is_accessible_for_free'] = isset($data['is_accessible_for_free']) ? $data['is_accessible_for_free'] : null;
        $this->container['maximum_attendee_capacity'] = isset($data['maximum_attendee_capacity']) ? $data['maximum_attendee_capacity'] : null;
        $this->container['opening_hours_specification'] = isset($data['opening_hours_specification']) ? $data['opening_hours_specification'] : null;
        $this->container['logo'] = isset($data['logo']) ? $data['logo'] : null;
        $this->container['photo'] = isset($data['photo']) ? $data['photo'] : null;
        $this->container['public_access'] = isset($data['public_access']) ? $data['public_access'] : null;
        $this->container['smoking_allowed'] = isset($data['smoking_allowed']) ? $data['smoking_allowed'] : null;
        $this->container['special_opening_hours_specification'] = isset($data['special_opening_hours_specification']) ? $data['special_opening_hours_specification'] : null;
        $this->container['telephone'] = isset($data['telephone']) ? $data['telephone'] : null;
        $this->container['tourist_type'] = isset($data['tourist_type']) ? $data['tourist_type'] : null;
        $this->container['located'] = isset($data['located']) ? $data['located'] : null;
        $this->container['copyright'] = isset($data['copyright']) ? $data['copyright'] : null;
        $this->container['detailed_information'] = isset($data['detailed_information']) ? $data['detailed_information'] : null;
        $this->container['title_teaser'] = isset($data['title_teaser']) ? $data['title_teaser'] : null;
        $this->container['text_teaser'] = isset($data['text_teaser']) ? $data['text_teaser'] : null;
        $this->container['public_transport'] = isset($data['public_transport']) ? $data['public_transport'] : null;
        $this->container['getting_there'] = isset($data['getting_there']) ? $data['getting_there'] : null;
        $this->container['opening_hours'] = isset($data['opening_hours']) ? $data['opening_hours'] : null;
        $this->container['parking'] = isset($data['parking']) ? $data['parking'] : null;
        $this->container['directions'] = isset($data['directions']) ? $data['directions'] : null;
        $this->container['fees'] = isset($data['fees']) ? $data['fees'] : null;
        $this->container['osm_id'] = isset($data['osm_id']) ? $data['osm_id'] : null;
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['tag'] = isset($data['tag']) ? $data['tag'] : null;
        $this->container['audio'] = isset($data['audio']) ? $data['audio'] : null;
        $this->container['video'] = isset($data['video']) ? $data['video'] : null;
        $this->container['amenity_feature'] = isset($data['amenity_feature']) ? $data['amenity_feature'] : null;
        $this->container['located_at'] = isset($data['located_at']) ? $data['located_at'] : null;
        $this->container['source_id'] = isset($data['source_id']) ? $data['source_id'] : null;
        $this->container['desired_vertex_root_node_id'] = isset($data['desired_vertex_root_node_id']) ? $data['desired_vertex_root_node_id'] : null;
        $this->container['data_governance'] = isset($data['data_governance']) ? $data['data_governance'] : null;
        $this->container['additional_property'] = isset($data['additional_property']) ? $data['additional_property'] : null;
        $this->container['external_ids'] = isset($data['external_ids']) ? $data['external_ids'] : null;
        $this->container['auto_translate'] = isset($data['auto_translate']) ? $data['auto_translate'] : null;
        $this->container['publish'] = isset($data['publish']) ? $data['publish'] : null;
        $this->container['is_deleted'] = isset($data['is_deleted']) ? $data['is_deleted'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['alternate_name'] = isset($data['alternate_name']) ? $data['alternate_name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['disambiguating_description'] = isset($data['disambiguating_description']) ? $data['disambiguating_description'] : null;
        $this->container['image'] = isset($data['image']) ? $data['image'] : null;
        $this->container['same_as'] = isset($data['same_as']) ? $data['same_as'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['additional_type'] = isset($data['additional_type']) ? $data['additional_type'] : null;
        $this->container['link'] = isset($data['link']) ? $data['link'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets winter_activity
     *
     * @return bool
     */
    public function getWinterActivity()
    {
        return $this->container['winter_activity'];
    }

    /**
     * Sets winter_activity
     *
     * @param bool $winter_activity winter_activity
     *
     * @return $this
     */
    public function setWinterActivity($winter_activity)
    {
        $this->container['winter_activity'] = $winter_activity;

        return $this;
    }

    /**
     * Gets length
     *
     * @return double
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param double $length length
     *
     * @return $this
     */
    public function setLength($length)
    {
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets time
     *
     * @return int
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time
     *
     * @param int $time time
     *
     * @return $this
     */
    public function setTime($time)
    {
        $this->container['time'] = $time;

        return $this;
    }

    /**
     * Gets elevation_json
     *
     * @return string
     */
    public function getElevationJson()
    {
        return $this->container['elevation_json'];
    }

    /**
     * Sets elevation_json
     *
     * @param string $elevation_json elevation_json
     *
     * @return $this
     */
    public function setElevationJson($elevation_json)
    {
        $this->container['elevation_json'] = $elevation_json;

        return $this;
    }

    /**
     * Gets elevation
     *
     * @return \InfocenterUpdate\Client\Model\DsTourElevationRequest
     */
    public function getElevation()
    {
        return $this->container['elevation'];
    }

    /**
     * Sets elevation
     *
     * @param \InfocenterUpdate\Client\Model\DsTourElevationRequest $elevation elevation
     *
     * @return $this
     */
    public function setElevation($elevation)
    {
        $this->container['elevation'] = $elevation;

        return $this;
    }

    /**
     * Gets rating_json
     *
     * @return string
     */
    public function getRatingJson()
    {
        return $this->container['rating_json'];
    }

    /**
     * Sets rating_json
     *
     * @param string $rating_json rating_json
     *
     * @return $this
     */
    public function setRatingJson($rating_json)
    {
        $this->container['rating_json'] = $rating_json;

        return $this;
    }

    /**
     * Gets rating
     *
     * @return \InfocenterUpdate\Client\Model\DsTourRatingRequest
     */
    public function getRating()
    {
        return $this->container['rating'];
    }

    /**
     * Sets rating
     *
     * @param \InfocenterUpdate\Client\Model\DsTourRatingRequest $rating rating
     *
     * @return $this
     */
    public function setRating($rating)
    {
        $this->container['rating'] = $rating;

        return $this;
    }

    /**
     * Gets season
     *
     * @return \InfocenterUpdate\Client\Model\DsTourSeasonRequest
     */
    public function getSeason()
    {
        return $this->container['season'];
    }

    /**
     * Sets season
     *
     * @param \InfocenterUpdate\Client\Model\DsTourSeasonRequest $season season
     *
     * @return $this
     */
    public function setSeason($season)
    {
        $this->container['season'] = $season;

        return $this;
    }

    /**
     * Gets risk_potential
     *
     * @return int
     */
    public function getRiskPotential()
    {
        return $this->container['risk_potential'];
    }

    /**
     * Sets risk_potential
     *
     * @param int $risk_potential risk_potential
     *
     * @return $this
     */
    public function setRiskPotential($risk_potential)
    {
        $this->container['risk_potential'] = $risk_potential;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state state
     *
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets title
     *
     * @return map[string,string]
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param map[string,string] $title title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets starting_point_description
     *
     * @return map[string,string]
     */
    public function getStartingPointDescription()
    {
        return $this->container['starting_point_description'];
    }

    /**
     * Sets starting_point_description
     *
     * @param map[string,string] $starting_point_description starting_point_description
     *
     * @return $this
     */
    public function setStartingPointDescription($starting_point_description)
    {
        $this->container['starting_point_description'] = $starting_point_description;

        return $this;
    }

    /**
     * Gets safety_guidelines
     *
     * @return map[string,string]
     */
    public function getSafetyGuidelines()
    {
        return $this->container['safety_guidelines'];
    }

    /**
     * Sets safety_guidelines
     *
     * @param map[string,string] $safety_guidelines safety_guidelines
     *
     * @return $this
     */
    public function setSafetyGuidelines($safety_guidelines)
    {
        $this->container['safety_guidelines'] = $safety_guidelines;

        return $this;
    }

    /**
     * Gets equipment
     *
     * @return map[string,string]
     */
    public function getEquipment()
    {
        return $this->container['equipment'];
    }

    /**
     * Sets equipment
     *
     * @param map[string,string] $equipment equipment
     *
     * @return $this
     */
    public function setEquipment($equipment)
    {
        $this->container['equipment'] = $equipment;

        return $this;
    }

    /**
     * Gets tip
     *
     * @return map[string,string]
     */
    public function getTip()
    {
        return $this->container['tip'];
    }

    /**
     * Sets tip
     *
     * @param map[string,string] $tip tip
     *
     * @return $this
     */
    public function setTip($tip)
    {
        $this->container['tip'] = $tip;

        return $this;
    }

    /**
     * Gets additional_information
     *
     * @return map[string,string]
     */
    public function getAdditionalInformation()
    {
        return $this->container['additional_information'];
    }

    /**
     * Sets additional_information
     *
     * @param map[string,string] $additional_information additional_information
     *
     * @return $this
     */
    public function setAdditionalInformation($additional_information)
    {
        $this->container['additional_information'] = $additional_information;

        return $this;
    }

    /**
     * Gets destination
     *
     * @return map[string,string]
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param map[string,string] $destination destination
     *
     * @return $this
     */
    public function setDestination($destination)
    {
        $this->container['destination'] = $destination;

        return $this;
    }

    /**
     * Gets track_signage
     *
     * @return map[string,string]
     */
    public function getTrackSignage()
    {
        return $this->container['track_signage'];
    }

    /**
     * Sets track_signage
     *
     * @param map[string,string] $track_signage track_signage
     *
     * @return $this
     */
    public function setTrackSignage($track_signage)
    {
        $this->container['track_signage'] = $track_signage;

        return $this;
    }

    /**
     * Gets literature
     *
     * @return map[string,string]
     */
    public function getLiterature()
    {
        return $this->container['literature'];
    }

    /**
     * Sets literature
     *
     * @param map[string,string] $literature literature
     *
     * @return $this
     */
    public function setLiterature($literature)
    {
        $this->container['literature'] = $literature;

        return $this;
    }

    /**
     * Gets maps
     *
     * @return map[string,string]
     */
    public function getMaps()
    {
        return $this->container['maps'];
    }

    /**
     * Sets maps
     *
     * @param map[string,string] $maps maps
     *
     * @return $this
     */
    public function setMaps($maps)
    {
        $this->container['maps'] = $maps;

        return $this;
    }

    /**
     * Gets duration
     *
     * @return string
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     *
     * @param string $duration duration
     *
     * @return $this
     */
    public function setDuration($duration)
    {
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets geo_destination
     *
     * @return \InfocenterUpdate\Client\Model\DsGeoCoordinatesRequest
     */
    public function getGeoDestination()
    {
        return $this->container['geo_destination'];
    }

    /**
     * Sets geo_destination
     *
     * @param \InfocenterUpdate\Client\Model\DsGeoCoordinatesRequest $geo_destination geo_destination
     *
     * @return $this
     */
    public function setGeoDestination($geo_destination)
    {
        $this->container['geo_destination'] = $geo_destination;

        return $this;
    }

    /**
     * Gets available_language
     *
     * @return string[]
     */
    public function getAvailableLanguage()
    {
        return $this->container['available_language'];
    }

    /**
     * Sets available_language
     *
     * @param string[] $available_language available_language
     *
     * @return $this
     */
    public function setAvailableLanguage($available_language)
    {
        $this->container['available_language'] = $available_language;

        return $this;
    }

    /**
     * Gets slogan
     *
     * @return string
     */
    public function getSlogan()
    {
        return $this->container['slogan'];
    }

    /**
     * Sets slogan
     *
     * @param string $slogan slogan
     *
     * @return $this
     */
    public function setSlogan($slogan)
    {
        $this->container['slogan'] = $slogan;

        return $this;
    }

    /**
     * Gets branch_code
     *
     * @return string
     */
    public function getBranchCode()
    {
        return $this->container['branch_code'];
    }

    /**
     * Sets branch_code
     *
     * @param string $branch_code branch_code
     *
     * @return $this
     */
    public function setBranchCode($branch_code)
    {
        $this->container['branch_code'] = $branch_code;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \InfocenterUpdate\Client\Model\DsPostalAddressRequest
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \InfocenterUpdate\Client\Model\DsPostalAddressRequest $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets fax_number
     *
     * @return string
     */
    public function getFaxNumber()
    {
        return $this->container['fax_number'];
    }

    /**
     * Sets fax_number
     *
     * @param string $fax_number fax_number
     *
     * @return $this
     */
    public function setFaxNumber($fax_number)
    {
        $this->container['fax_number'] = $fax_number;

        return $this;
    }

    /**
     * Gets geo
     *
     * @return \InfocenterUpdate\Client\Model\DsGeoCoordinatesRequest
     */
    public function getGeo()
    {
        return $this->container['geo'];
    }

    /**
     * Sets geo
     *
     * @param \InfocenterUpdate\Client\Model\DsGeoCoordinatesRequest $geo geo
     *
     * @return $this
     */
    public function setGeo($geo)
    {
        $this->container['geo'] = $geo;

        return $this;
    }

    /**
     * Gets geo_shape
     *
     * @return \InfocenterUpdate\Client\Model\DsGeoShapeRequest
     */
    public function getGeoShape()
    {
        return $this->container['geo_shape'];
    }

    /**
     * Sets geo_shape
     *
     * @param \InfocenterUpdate\Client\Model\DsGeoShapeRequest $geo_shape geo_shape
     *
     * @return $this
     */
    public function setGeoShape($geo_shape)
    {
        $this->container['geo_shape'] = $geo_shape;

        return $this;
    }

    /**
     * Gets has_map
     *
     * @return string
     */
    public function getHasMap()
    {
        return $this->container['has_map'];
    }

    /**
     * Sets has_map
     *
     * @param string $has_map has_map
     *
     * @return $this
     */
    public function setHasMap($has_map)
    {
        $this->container['has_map'] = $has_map;

        return $this;
    }

    /**
     * Gets is_accessible_for_free
     *
     * @return bool
     */
    public function getIsAccessibleForFree()
    {
        return $this->container['is_accessible_for_free'];
    }

    /**
     * Sets is_accessible_for_free
     *
     * @param bool $is_accessible_for_free is_accessible_for_free
     *
     * @return $this
     */
    public function setIsAccessibleForFree($is_accessible_for_free)
    {
        $this->container['is_accessible_for_free'] = $is_accessible_for_free;

        return $this;
    }

    /**
     * Gets maximum_attendee_capacity
     *
     * @return int
     */
    public function getMaximumAttendeeCapacity()
    {
        return $this->container['maximum_attendee_capacity'];
    }

    /**
     * Sets maximum_attendee_capacity
     *
     * @param int $maximum_attendee_capacity maximum_attendee_capacity
     *
     * @return $this
     */
    public function setMaximumAttendeeCapacity($maximum_attendee_capacity)
    {
        $this->container['maximum_attendee_capacity'] = $maximum_attendee_capacity;

        return $this;
    }

    /**
     * Gets opening_hours_specification
     *
     * @return \InfocenterUpdate\Client\Model\DsOpeningHoursSpecificationRequest[]
     */
    public function getOpeningHoursSpecification()
    {
        return $this->container['opening_hours_specification'];
    }

    /**
     * Sets opening_hours_specification
     *
     * @param \InfocenterUpdate\Client\Model\DsOpeningHoursSpecificationRequest[] $opening_hours_specification opening_hours_specification
     *
     * @return $this
     */
    public function setOpeningHoursSpecification($opening_hours_specification)
    {
        $this->container['opening_hours_specification'] = $opening_hours_specification;

        return $this;
    }

    /**
     * Gets logo
     *
     * @return \InfocenterUpdate\Client\Model\DsImageObjectRequest
     */
    public function getLogo()
    {
        return $this->container['logo'];
    }

    /**
     * Sets logo
     *
     * @param \InfocenterUpdate\Client\Model\DsImageObjectRequest $logo logo
     *
     * @return $this
     */
    public function setLogo($logo)
    {
        $this->container['logo'] = $logo;

        return $this;
    }

    /**
     * Gets photo
     *
     * @return \InfocenterUpdate\Client\Model\DsImageObjectRequest[]
     */
    public function getPhoto()
    {
        return $this->container['photo'];
    }

    /**
     * Sets photo
     *
     * @param \InfocenterUpdate\Client\Model\DsImageObjectRequest[] $photo photo
     *
     * @return $this
     */
    public function setPhoto($photo)
    {
        $this->container['photo'] = $photo;

        return $this;
    }

    /**
     * Gets public_access
     *
     * @return bool
     */
    public function getPublicAccess()
    {
        return $this->container['public_access'];
    }

    /**
     * Sets public_access
     *
     * @param bool $public_access public_access
     *
     * @return $this
     */
    public function setPublicAccess($public_access)
    {
        $this->container['public_access'] = $public_access;

        return $this;
    }

    /**
     * Gets smoking_allowed
     *
     * @return bool
     */
    public function getSmokingAllowed()
    {
        return $this->container['smoking_allowed'];
    }

    /**
     * Sets smoking_allowed
     *
     * @param bool $smoking_allowed smoking_allowed
     *
     * @return $this
     */
    public function setSmokingAllowed($smoking_allowed)
    {
        $this->container['smoking_allowed'] = $smoking_allowed;

        return $this;
    }

    /**
     * Gets special_opening_hours_specification
     *
     * @return \InfocenterUpdate\Client\Model\DsOpeningHoursSpecificationRequest[]
     */
    public function getSpecialOpeningHoursSpecification()
    {
        return $this->container['special_opening_hours_specification'];
    }

    /**
     * Sets special_opening_hours_specification
     *
     * @param \InfocenterUpdate\Client\Model\DsOpeningHoursSpecificationRequest[] $special_opening_hours_specification special_opening_hours_specification
     *
     * @return $this
     */
    public function setSpecialOpeningHoursSpecification($special_opening_hours_specification)
    {
        $this->container['special_opening_hours_specification'] = $special_opening_hours_specification;

        return $this;
    }

    /**
     * Gets telephone
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->container['telephone'];
    }

    /**
     * Sets telephone
     *
     * @param string $telephone telephone
     *
     * @return $this
     */
    public function setTelephone($telephone)
    {
        $this->container['telephone'] = $telephone;

        return $this;
    }

    /**
     * Gets tourist_type
     *
     * @return string
     */
    public function getTouristType()
    {
        return $this->container['tourist_type'];
    }

    /**
     * Sets tourist_type
     *
     * @param string $tourist_type tourist_type
     *
     * @return $this
     */
    public function setTouristType($tourist_type)
    {
        $this->container['tourist_type'] = $tourist_type;

        return $this;
    }

    /**
     * Gets located
     *
     * @return string[]
     */
    public function getLocated()
    {
        return $this->container['located'];
    }

    /**
     * Sets located
     *
     * @param string[] $located located
     *
     * @return $this
     */
    public function setLocated($located)
    {
        $this->container['located'] = $located;

        return $this;
    }

    /**
     * Gets copyright
     *
     * @return map[string,string]
     */
    public function getCopyright()
    {
        return $this->container['copyright'];
    }

    /**
     * Sets copyright
     *
     * @param map[string,string] $copyright copyright
     *
     * @return $this
     */
    public function setCopyright($copyright)
    {
        $this->container['copyright'] = $copyright;

        return $this;
    }

    /**
     * Gets detailed_information
     *
     * @return map[string,\InfocenterUpdate\Client\Model\DsIEnumerableString]
     */
    public function getDetailedInformation()
    {
        return $this->container['detailed_information'];
    }

    /**
     * Sets detailed_information
     *
     * @param map[string,\InfocenterUpdate\Client\Model\DsIEnumerableString] $detailed_information detailed_information
     *
     * @return $this
     */
    public function setDetailedInformation($detailed_information)
    {
        $this->container['detailed_information'] = $detailed_information;

        return $this;
    }

    /**
     * Gets title_teaser
     *
     * @return map[string,string]
     */
    public function getTitleTeaser()
    {
        return $this->container['title_teaser'];
    }

    /**
     * Sets title_teaser
     *
     * @param map[string,string] $title_teaser title_teaser
     *
     * @return $this
     */
    public function setTitleTeaser($title_teaser)
    {
        $this->container['title_teaser'] = $title_teaser;

        return $this;
    }

    /**
     * Gets text_teaser
     *
     * @return map[string,string]
     */
    public function getTextTeaser()
    {
        return $this->container['text_teaser'];
    }

    /**
     * Sets text_teaser
     *
     * @param map[string,string] $text_teaser text_teaser
     *
     * @return $this
     */
    public function setTextTeaser($text_teaser)
    {
        $this->container['text_teaser'] = $text_teaser;

        return $this;
    }

    /**
     * Gets public_transport
     *
     * @return map[string,string]
     */
    public function getPublicTransport()
    {
        return $this->container['public_transport'];
    }

    /**
     * Sets public_transport
     *
     * @param map[string,string] $public_transport public_transport
     *
     * @return $this
     */
    public function setPublicTransport($public_transport)
    {
        $this->container['public_transport'] = $public_transport;

        return $this;
    }

    /**
     * Gets getting_there
     *
     * @return map[string,string]
     */
    public function getGettingThere()
    {
        return $this->container['getting_there'];
    }

    /**
     * Sets getting_there
     *
     * @param map[string,string] $getting_there getting_there
     *
     * @return $this
     */
    public function setGettingThere($getting_there)
    {
        $this->container['getting_there'] = $getting_there;

        return $this;
    }

    /**
     * Gets opening_hours
     *
     * @return map[string,string]
     */
    public function getOpeningHours()
    {
        return $this->container['opening_hours'];
    }

    /**
     * Sets opening_hours
     *
     * @param map[string,string] $opening_hours opening_hours
     *
     * @return $this
     */
    public function setOpeningHours($opening_hours)
    {
        $this->container['opening_hours'] = $opening_hours;

        return $this;
    }

    /**
     * Gets parking
     *
     * @return map[string,string]
     */
    public function getParking()
    {
        return $this->container['parking'];
    }

    /**
     * Sets parking
     *
     * @param map[string,string] $parking parking
     *
     * @return $this
     */
    public function setParking($parking)
    {
        $this->container['parking'] = $parking;

        return $this;
    }

    /**
     * Gets directions
     *
     * @return map[string,string]
     */
    public function getDirections()
    {
        return $this->container['directions'];
    }

    /**
     * Sets directions
     *
     * @param map[string,string] $directions directions
     *
     * @return $this
     */
    public function setDirections($directions)
    {
        $this->container['directions'] = $directions;

        return $this;
    }

    /**
     * Gets fees
     *
     * @return map[string,string]
     */
    public function getFees()
    {
        return $this->container['fees'];
    }

    /**
     * Sets fees
     *
     * @param map[string,string] $fees fees
     *
     * @return $this
     */
    public function setFees($fees)
    {
        $this->container['fees'] = $fees;

        return $this;
    }

    /**
     * Gets osm_id
     *
     * @return string
     */
    public function getOsmId()
    {
        return $this->container['osm_id'];
    }

    /**
     * Sets osm_id
     *
     * @param string $osm_id osm_id
     *
     * @return $this
     */
    public function setOsmId($osm_id)
    {
        $this->container['osm_id'] = $osm_id;

        return $this;
    }

    /**
     * Gets category
     *
     * @return string[]
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param string[] $category category
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets tag
     *
     * @return string[]
     */
    public function getTag()
    {
        return $this->container['tag'];
    }

    /**
     * Sets tag
     *
     * @param string[] $tag tag
     *
     * @return $this
     */
    public function setTag($tag)
    {
        $this->container['tag'] = $tag;

        return $this;
    }

    /**
     * Gets audio
     *
     * @return \InfocenterUpdate\Client\Model\DsAudioObjectRequest[]
     */
    public function getAudio()
    {
        return $this->container['audio'];
    }

    /**
     * Sets audio
     *
     * @param \InfocenterUpdate\Client\Model\DsAudioObjectRequest[] $audio audio
     *
     * @return $this
     */
    public function setAudio($audio)
    {
        $this->container['audio'] = $audio;

        return $this;
    }

    /**
     * Gets video
     *
     * @return \InfocenterUpdate\Client\Model\DsVideoObjectRequest[]
     */
    public function getVideo()
    {
        return $this->container['video'];
    }

    /**
     * Sets video
     *
     * @param \InfocenterUpdate\Client\Model\DsVideoObjectRequest[] $video video
     *
     * @return $this
     */
    public function setVideo($video)
    {
        $this->container['video'] = $video;

        return $this;
    }

    /**
     * Gets amenity_feature
     *
     * @return \InfocenterUpdate\Client\Model\DsLocationFeatureSpecificationRequest[]
     */
    public function getAmenityFeature()
    {
        return $this->container['amenity_feature'];
    }

    /**
     * Sets amenity_feature
     *
     * @param \InfocenterUpdate\Client\Model\DsLocationFeatureSpecificationRequest[] $amenity_feature amenity_feature
     *
     * @return $this
     */
    public function setAmenityFeature($amenity_feature)
    {
        $this->container['amenity_feature'] = $amenity_feature;

        return $this;
    }

    /**
     * Gets located_at
     *
     * @return string
     */
    public function getLocatedAt()
    {
        return $this->container['located_at'];
    }

    /**
     * Sets located_at
     *
     * @param string $located_at located_at
     *
     * @return $this
     */
    public function setLocatedAt($located_at)
    {
        $this->container['located_at'] = $located_at;

        return $this;
    }

    /**
     * Gets source_id
     *
     * @return string
     */
    public function getSourceId()
    {
        return $this->container['source_id'];
    }

    /**
     * Sets source_id
     *
     * @param string $source_id source_id
     *
     * @return $this
     */
    public function setSourceId($source_id)
    {
        $this->container['source_id'] = $source_id;

        return $this;
    }

    /**
     * Gets desired_vertex_root_node_id
     *
     * @return string
     */
    public function getDesiredVertexRootNodeId()
    {
        return $this->container['desired_vertex_root_node_id'];
    }

    /**
     * Sets desired_vertex_root_node_id
     *
     * @param string $desired_vertex_root_node_id desired_vertex_root_node_id
     *
     * @return $this
     */
    public function setDesiredVertexRootNodeId($desired_vertex_root_node_id)
    {
        $this->container['desired_vertex_root_node_id'] = $desired_vertex_root_node_id;

        return $this;
    }

    /**
     * Gets data_governance
     *
     * @return \InfocenterUpdate\Client\Model\DsDataGovernanceRequest
     */
    public function getDataGovernance()
    {
        return $this->container['data_governance'];
    }

    /**
     * Sets data_governance
     *
     * @param \InfocenterUpdate\Client\Model\DsDataGovernanceRequest $data_governance data_governance
     *
     * @return $this
     */
    public function setDataGovernance($data_governance)
    {
        $this->container['data_governance'] = $data_governance;

        return $this;
    }

    /**
     * Gets additional_property
     *
     * @return \InfocenterUpdate\Client\Model\DsPropertyValueRequest[]
     */
    public function getAdditionalProperty()
    {
        return $this->container['additional_property'];
    }

    /**
     * Sets additional_property
     *
     * @param \InfocenterUpdate\Client\Model\DsPropertyValueRequest[] $additional_property additional_property
     *
     * @return $this
     */
    public function setAdditionalProperty($additional_property)
    {
        $this->container['additional_property'] = $additional_property;

        return $this;
    }

    /**
     * Gets external_ids
     *
     * @return \InfocenterUpdate\Client\Model\DsExternalIds
     */
    public function getExternalIds()
    {
        return $this->container['external_ids'];
    }

    /**
     * Sets external_ids
     *
     * @param \InfocenterUpdate\Client\Model\DsExternalIds $external_ids external_ids
     *
     * @return $this
     */
    public function setExternalIds($external_ids)
    {
        $this->container['external_ids'] = $external_ids;

        return $this;
    }

    /**
     * Gets auto_translate
     *
     * @return bool
     */
    public function getAutoTranslate()
    {
        return $this->container['auto_translate'];
    }

    /**
     * Sets auto_translate
     *
     * @param bool $auto_translate auto_translate
     *
     * @return $this
     */
    public function setAutoTranslate($auto_translate)
    {
        $this->container['auto_translate'] = $auto_translate;

        return $this;
    }

    /**
     * Gets publish
     *
     * @return bool
     */
    public function getPublish()
    {
        return $this->container['publish'];
    }

    /**
     * Sets publish
     *
     * @param bool $publish publish
     *
     * @return $this
     */
    public function setPublish($publish)
    {
        $this->container['publish'] = $publish;

        return $this;
    }

    /**
     * Gets is_deleted
     *
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->container['is_deleted'];
    }

    /**
     * Sets is_deleted
     *
     * @param bool $is_deleted is_deleted
     *
     * @return $this
     */
    public function setIsDeleted($is_deleted)
    {
        $this->container['is_deleted'] = $is_deleted;

        return $this;
    }

    /**
     * Gets name
     *
     * @return map[string,string]
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param map[string,string] $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets alternate_name
     *
     * @return map[string,string]
     */
    public function getAlternateName()
    {
        return $this->container['alternate_name'];
    }

    /**
     * Sets alternate_name
     *
     * @param map[string,string] $alternate_name alternate_name
     *
     * @return $this
     */
    public function setAlternateName($alternate_name)
    {
        $this->container['alternate_name'] = $alternate_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return map[string,string]
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param map[string,string] $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets disambiguating_description
     *
     * @return map[string,string]
     */
    public function getDisambiguatingDescription()
    {
        return $this->container['disambiguating_description'];
    }

    /**
     * Sets disambiguating_description
     *
     * @param map[string,string] $disambiguating_description disambiguating_description
     *
     * @return $this
     */
    public function setDisambiguatingDescription($disambiguating_description)
    {
        $this->container['disambiguating_description'] = $disambiguating_description;

        return $this;
    }

    /**
     * Gets image
     *
     * @return \InfocenterUpdate\Client\Model\DsImageObjectRequest
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param \InfocenterUpdate\Client\Model\DsImageObjectRequest $image image
     *
     * @return $this
     */
    public function setImage($image)
    {
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets same_as
     *
     * @return string
     */
    public function getSameAs()
    {
        return $this->container['same_as'];
    }

    /**
     * Sets same_as
     *
     * @param string $same_as same_as
     *
     * @return $this
     */
    public function setSameAs($same_as)
    {
        $this->container['same_as'] = $same_as;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets additional_type
     *
     * @return string
     */
    public function getAdditionalType()
    {
        return $this->container['additional_type'];
    }

    /**
     * Sets additional_type
     *
     * @param string $additional_type additional_type
     *
     * @return $this
     */
    public function setAdditionalType($additional_type)
    {
        $this->container['additional_type'] = $additional_type;

        return $this;
    }

    /**
     * Gets link
     *
     * @return \InfocenterUpdate\Client\Model\DsLinkRequest[]
     */
    public function getLink()
    {
        return $this->container['link'];
    }

    /**
     * Sets link
     *
     * @param \InfocenterUpdate\Client\Model\DsLinkRequest[] $link link
     *
     * @return $this
     */
    public function setLink($link)
    {
        $this->container['link'] = $link;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
