<?php
/**
 * DsAccommodationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InfocenterUpdate-TEST-V2
 *
 * Infocenter Update API
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InfocenterUpdate\Client;

use PHPUnit\Framework\TestCase;

/**
 * DsAccommodationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DsAccommodationRequest
 * @package     InfocenterUpdate\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsAccommodationRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DsAccommodationRequest"
     */
    public function testDsAccommodationRequest()
    {
    }

    /**
     * Test attribute "accommodation_category"
     */
    public function testPropertyAccommodationCategory()
    {
    }

    /**
     * Test attribute "floor_level"
     */
    public function testPropertyFloorLevel()
    {
    }

    /**
     * Test attribute "permitted_usage"
     */
    public function testPropertyPermittedUsage()
    {
    }

    /**
     * Test attribute "bed"
     */
    public function testPropertyBed()
    {
    }

    /**
     * Test attribute "floor_size"
     */
    public function testPropertyFloorSize()
    {
    }

    /**
     * Test attribute "number_of_bedrooms"
     */
    public function testPropertyNumberOfBedrooms()
    {
    }

    /**
     * Test attribute "number_of_rooms"
     */
    public function testPropertyNumberOfRooms()
    {
    }

    /**
     * Test attribute "number_of_bathrooms"
     */
    public function testPropertyNumberOfBathrooms()
    {
    }

    /**
     * Test attribute "occupancy"
     */
    public function testPropertyOccupancy()
    {
    }

    /**
     * Test attribute "lease_length"
     */
    public function testPropertyLeaseLength()
    {
    }

    /**
     * Test attribute "pets_allowed"
     */
    public function testPropertyPetsAllowed()
    {
    }

    /**
     * Test attribute "year_built"
     */
    public function testPropertyYearBuilt()
    {
    }

    /**
     * Test attribute "available_language"
     */
    public function testPropertyAvailableLanguage()
    {
    }

    /**
     * Test attribute "slogan"
     */
    public function testPropertySlogan()
    {
    }

    /**
     * Test attribute "branch_code"
     */
    public function testPropertyBranchCode()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "fax_number"
     */
    public function testPropertyFaxNumber()
    {
    }

    /**
     * Test attribute "geo"
     */
    public function testPropertyGeo()
    {
    }

    /**
     * Test attribute "geo_shape"
     */
    public function testPropertyGeoShape()
    {
    }

    /**
     * Test attribute "has_map"
     */
    public function testPropertyHasMap()
    {
    }

    /**
     * Test attribute "is_accessible_for_free"
     */
    public function testPropertyIsAccessibleForFree()
    {
    }

    /**
     * Test attribute "maximum_attendee_capacity"
     */
    public function testPropertyMaximumAttendeeCapacity()
    {
    }

    /**
     * Test attribute "opening_hours_specification"
     */
    public function testPropertyOpeningHoursSpecification()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "photo"
     */
    public function testPropertyPhoto()
    {
    }

    /**
     * Test attribute "public_access"
     */
    public function testPropertyPublicAccess()
    {
    }

    /**
     * Test attribute "smoking_allowed"
     */
    public function testPropertySmokingAllowed()
    {
    }

    /**
     * Test attribute "special_opening_hours_specification"
     */
    public function testPropertySpecialOpeningHoursSpecification()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "tourist_type"
     */
    public function testPropertyTouristType()
    {
    }

    /**
     * Test attribute "located"
     */
    public function testPropertyLocated()
    {
    }

    /**
     * Test attribute "copyright"
     */
    public function testPropertyCopyright()
    {
    }

    /**
     * Test attribute "detailed_information"
     */
    public function testPropertyDetailedInformation()
    {
    }

    /**
     * Test attribute "title_teaser"
     */
    public function testPropertyTitleTeaser()
    {
    }

    /**
     * Test attribute "text_teaser"
     */
    public function testPropertyTextTeaser()
    {
    }

    /**
     * Test attribute "public_transport"
     */
    public function testPropertyPublicTransport()
    {
    }

    /**
     * Test attribute "getting_there"
     */
    public function testPropertyGettingThere()
    {
    }

    /**
     * Test attribute "opening_hours"
     */
    public function testPropertyOpeningHours()
    {
    }

    /**
     * Test attribute "parking"
     */
    public function testPropertyParking()
    {
    }

    /**
     * Test attribute "directions"
     */
    public function testPropertyDirections()
    {
    }

    /**
     * Test attribute "fees"
     */
    public function testPropertyFees()
    {
    }

    /**
     * Test attribute "osm_id"
     */
    public function testPropertyOsmId()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "audio"
     */
    public function testPropertyAudio()
    {
    }

    /**
     * Test attribute "video"
     */
    public function testPropertyVideo()
    {
    }

    /**
     * Test attribute "amenity_feature"
     */
    public function testPropertyAmenityFeature()
    {
    }

    /**
     * Test attribute "located_at"
     */
    public function testPropertyLocatedAt()
    {
    }

    /**
     * Test attribute "source_id"
     */
    public function testPropertySourceId()
    {
    }

    /**
     * Test attribute "desired_vertex_root_node_id"
     */
    public function testPropertyDesiredVertexRootNodeId()
    {
    }

    /**
     * Test attribute "data_governance"
     */
    public function testPropertyDataGovernance()
    {
    }

    /**
     * Test attribute "additional_property"
     */
    public function testPropertyAdditionalProperty()
    {
    }

    /**
     * Test attribute "external_ids"
     */
    public function testPropertyExternalIds()
    {
    }

    /**
     * Test attribute "auto_translate"
     */
    public function testPropertyAutoTranslate()
    {
    }

    /**
     * Test attribute "publish"
     */
    public function testPropertyPublish()
    {
    }

    /**
     * Test attribute "is_deleted"
     */
    public function testPropertyIsDeleted()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "alternate_name"
     */
    public function testPropertyAlternateName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "disambiguating_description"
     */
    public function testPropertyDisambiguatingDescription()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "same_as"
     */
    public function testPropertySameAs()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "additional_type"
     */
    public function testPropertyAdditionalType()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }
}
