<?php
/**
 * DsGeoShapeRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InfocenterUpdate-TEST
 *
 * Infocenter Update test-v2
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InfocenterUpdate\Client;

/**
 * DsGeoShapeRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DsGeoShapeRequest
 * @package     InfocenterUpdate\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsGeoShapeRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsGeoShapeRequest"
     */
    public function testDsGeoShapeRequest()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "address_country"
     */
    public function testPropertyAddressCountry()
    {
    }

    /**
     * Test attribute "elevation"
     */
    public function testPropertyElevation()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "box"
     */
    public function testPropertyBox()
    {
    }

    /**
     * Test attribute "circle"
     */
    public function testPropertyCircle()
    {
    }

    /**
     * Test attribute "line"
     */
    public function testPropertyLine()
    {
    }

    /**
     * Test attribute "polygon"
     */
    public function testPropertyPolygon()
    {
    }

    /**
     * Test attribute "multiline"
     */
    public function testPropertyMultiline()
    {
    }

    /**
     * Test attribute "additional_type"
     */
    public function testPropertyAdditionalType()
    {
    }

    /**
     * Test attribute "alternate_name"
     */
    public function testPropertyAlternateName()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "same_as"
     */
    public function testPropertySameAs()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "disambiguating_description"
     */
    public function testPropertyDisambiguatingDescription()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }
}
