<?php
/**
 * DsTourRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InfocenterUpdate-TEST
 *
 * Infocenter Update test-v2
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InfocenterUpdate\Client;

/**
 * DsTourRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DsTourRequest
 * @package     InfocenterUpdate\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsTourRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsTourRequest"
     */
    public function testDsTourRequest()
    {
    }

    /**
     * Test attribute "winter_activity"
     */
    public function testPropertyWinterActivity()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "elevation"
     */
    public function testPropertyElevation()
    {
    }

    /**
     * Test attribute "rating"
     */
    public function testPropertyRating()
    {
    }

    /**
     * Test attribute "season"
     */
    public function testPropertySeason()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "starting_point_description"
     */
    public function testPropertyStartingPointDescription()
    {
    }

    /**
     * Test attribute "safety_guidelines"
     */
    public function testPropertySafetyGuidelines()
    {
    }

    /**
     * Test attribute "equipment"
     */
    public function testPropertyEquipment()
    {
    }

    /**
     * Test attribute "tip"
     */
    public function testPropertyTip()
    {
    }

    /**
     * Test attribute "additional_information"
     */
    public function testPropertyAdditionalInformation()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "track_signage"
     */
    public function testPropertyTrackSignage()
    {
    }

    /**
     * Test attribute "literature"
     */
    public function testPropertyLiterature()
    {
    }

    /**
     * Test attribute "maps"
     */
    public function testPropertyMaps()
    {
    }

    /**
     * Test attribute "source_id"
     */
    public function testPropertySourceId()
    {
    }

    /**
     * Test attribute "auto_translate"
     */
    public function testPropertyAutoTranslate()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "geo"
     */
    public function testPropertyGeo()
    {
    }

    /**
     * Test attribute "geo_shape"
     */
    public function testPropertyGeoShape()
    {
    }

    /**
     * Test attribute "is_accessible_for_free"
     */
    public function testPropertyIsAccessibleForFree()
    {
    }

    /**
     * Test attribute "maximum_attendee_capacity"
     */
    public function testPropertyMaximumAttendeeCapacity()
    {
    }

    /**
     * Test attribute "photo"
     */
    public function testPropertyPhoto()
    {
    }

    /**
     * Test attribute "public_access"
     */
    public function testPropertyPublicAccess()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "located"
     */
    public function testPropertyLocated()
    {
    }

    /**
     * Test attribute "available_language"
     */
    public function testPropertyAvailableLanguage()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "osm_id"
     */
    public function testPropertyOsmId()
    {
    }

    /**
     * Test attribute "public_transport"
     */
    public function testPropertyPublicTransport()
    {
    }

    /**
     * Test attribute "getting_there"
     */
    public function testPropertyGettingThere()
    {
    }

    /**
     * Test attribute "parking"
     */
    public function testPropertyParking()
    {
    }

    /**
     * Test attribute "directions"
     */
    public function testPropertyDirections()
    {
    }

    /**
     * Test attribute "fees"
     */
    public function testPropertyFees()
    {
    }

    /**
     * Test attribute "data_governance"
     */
    public function testPropertyDataGovernance()
    {
    }

    /**
     * Test attribute "additional_type"
     */
    public function testPropertyAdditionalType()
    {
    }

    /**
     * Test attribute "alternate_name"
     */
    public function testPropertyAlternateName()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "same_as"
     */
    public function testPropertySameAs()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "disambiguating_description"
     */
    public function testPropertyDisambiguatingDescription()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }
}
