<?php
/**
 * DsTourElevationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InfocenterUpdate-TEST
 *
 * Infocenter Update test-v2
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InfocenterUpdate\Client;

/**
 * DsTourElevationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DsTourElevationRequest
 * @package     InfocenterUpdate\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsTourElevationRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DsTourElevationRequest"
     */
    public function testDsTourElevationRequest()
    {
    }

    /**
     * Test attribute "ascent"
     */
    public function testPropertyAscent()
    {
    }

    /**
     * Test attribute "descent"
     */
    public function testPropertyDescent()
    {
    }

    /**
     * Test attribute "min_altitude"
     */
    public function testPropertyMinAltitude()
    {
    }

    /**
     * Test attribute "max_altitude"
     */
    public function testPropertyMaxAltitude()
    {
    }
}
