<?php
/**
 * DsVideoObjectRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InfocenterUpdate-TEST-V2
 *
 * Infocenter Update API
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InfocenterUpdate\Client;

use PHPUnit\Framework\TestCase;

/**
 * DsVideoObjectRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DsVideoObjectRequest
 * @package     InfocenterUpdate\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DsVideoObjectRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DsVideoObjectRequest"
     */
    public function testDsVideoObjectRequest()
    {
    }

    /**
     * Test attribute "content_size"
     */
    public function testPropertyContentSize()
    {
    }

    /**
     * Test attribute "content_url"
     */
    public function testPropertyContentUrl()
    {
    }

    /**
     * Test attribute "embed_url"
     */
    public function testPropertyEmbedUrl()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "caption"
     */
    public function testPropertyCaption()
    {
    }

    /**
     * Test attribute "content_reference_time"
     */
    public function testPropertyContentReferenceTime()
    {
    }

    /**
     * Test attribute "copyright_year"
     */
    public function testPropertyCopyrightYear()
    {
    }

    /**
     * Test attribute "encoding_format"
     */
    public function testPropertyEncodingFormat()
    {
    }

    /**
     * Test attribute "is_accessible_for_free"
     */
    public function testPropertyIsAccessibleForFree()
    {
    }

    /**
     * Test attribute "thumbnail_url"
     */
    public function testPropertyThumbnailUrl()
    {
    }

    /**
     * Test attribute "in_language"
     */
    public function testPropertyInLanguage()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "contained_in_place"
     */
    public function testPropertyContainedInPlace()
    {
    }

    /**
     * Test attribute "photo"
     */
    public function testPropertyPhoto()
    {
    }

    /**
     * Test attribute "source_id"
     */
    public function testPropertySourceId()
    {
    }

    /**
     * Test attribute "desired_vertex_root_node_id"
     */
    public function testPropertyDesiredVertexRootNodeId()
    {
    }

    /**
     * Test attribute "data_governance"
     */
    public function testPropertyDataGovernance()
    {
    }

    /**
     * Test attribute "additional_property"
     */
    public function testPropertyAdditionalProperty()
    {
    }

    /**
     * Test attribute "external_ids"
     */
    public function testPropertyExternalIds()
    {
    }

    /**
     * Test attribute "auto_translate"
     */
    public function testPropertyAutoTranslate()
    {
    }

    /**
     * Test attribute "publish"
     */
    public function testPropertyPublish()
    {
    }

    /**
     * Test attribute "is_deleted"
     */
    public function testPropertyIsDeleted()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "alternate_name"
     */
    public function testPropertyAlternateName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "disambiguating_description"
     */
    public function testPropertyDisambiguatingDescription()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "same_as"
     */
    public function testPropertySameAs()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "additional_type"
     */
    public function testPropertyAdditionalType()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }
}
