<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InfocenterUpdate-TEST
 *
 * Infocenter Update test-v2
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace InfocenterUpdate\Client;

use InfocenterUpdate\Client\Configuration;
use InfocenterUpdate\Client\ApiException;
use InfocenterUpdate\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  InfocenterUpdate\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteCreativeWork
     *
     * DeleteCreativeWork.
     *
     */
    public function testDeleteCreativeWork()
    {
    }

    /**
     * Test case for getStatus
     *
     * GetStatus.
     *
     */
    public function testGetStatus()
    {
    }

    /**
     * Test case for getStatusAbout
     *
     * GetStatusAbout.
     *
     */
    public function testGetStatusAbout()
    {
    }

    /**
     * Test case for postUpsertCreativeWork
     *
     * PostUpsertCreativeWork.
     *
     */
    public function testPostUpsertCreativeWork()
    {
    }

    /**
     * Test case for putUpsertCreativeWork
     *
     * PutUpsertCreativeWork.
     *
     */
    public function testPutUpsertCreativeWork()
    {
    }
}
